name: Deploy to Server 

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Run the job on an Ubuntu runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2  # Checkout your repository's code

      # - name: Set up SSH private key
      #   uses: appleboy/ssh-action@master  # Use Appleboy's SSH Action
      #   with:
      #     host: ${{ secrets.HOST }}  # Server's IP address or hostname
      #     username: ${{ secrets.USERNAME }}  # SSH username (e.g., ubuntu for AWS EC2)
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}  # The private SSH key secret
      #     port: 22  # SSH port (default is 22)
          script: |
                ls
                cd Backend
                ls
                npm i
                npm start
                pm2 restart 1
